PR_TITLE_REGEX: '(^[A-z]+(-| )[0-9]+(:|-| )(\w|\W)+$)'
COMMIT_MESSAGE_REGEX: '(?=.*(^((build:|chore:|ci:|docs:|feat:|fix:|perf:|refactor:|revert:|update:|create:|style:|test:)(( )|())([a-z]\w{1,72})))|(Merge (.*\s*)*)|(Initial commit$))(?=.*([A-z]+(-)[0-9]))'
OUTPUT_TITLE_FAIL: <h3>Message validation failed!!!</h3>
OUTPUT_TITLE_SUCCESS: Message validation passed!!!
VALID_COMMIT_MESSAGE: Commit messages are valid
INVALID_COMMIT_MESSAGE: Commit messages are invalid
SINGLE_OTHER_INVALID_MESSAGE: other message is invalid
MULTIPLE_OTHER_INVALID_MESSAGE: other messages are invalid
VALID_PULL_REQUEST_MESSAGE: Pull request title is valid
INVALID_PULL_REQUEST_MESSAGE: Pull request title is invalid
